name: Deploy Backend en Render
on:
  push:
    branches: [main]
    paths:
      - 'FablabBackEnd/**'
      - '.github/workflows/deploy-backend.yml'

    workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout al codigo
        uses: actions/checkout@v4

      - name: configurar NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Instalar dependencias del Backend
        run: cd FablabBackEnd && npm ci

      - name: Run linter
        run: cd FablabBackEnd && npm run lint || true

      - name: Deploy a Render
        uses: JorgeLNJunior/render-deploy@v1.4.6
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true

      - name: Exito en Deploy
        run: echo "Backend Lanzado"